=== dctdevelopment/bagri/etc/samples/tpox/custacc.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema targetNamespace="http://tpox-benchmark.com/custacc" xmlns:custacc="http://tpox-benchmark.com/custacc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" > 
	
	<xsd:complexType name="PhoneType"> 
		<xsd:sequence> 
			<xsd:element name="CountryCode" type="xsd:string"/> 
			<xsd:element name="AreaCode" type="xsd:string"/> 
			<xsd:element name="Number" type="xsd:string"/> 
			<xsd:element name="Extension" type="xsd:string" minOccurs="0"/> 
		</xsd:sequence> 
		<xsd:attribute name="primary" use="required"> 
			<xsd:simpleType> 
				<xsd:restriction base="xsd:NMTOKEN"> 
					<xsd:enumeration value="Yes"/> 
					<xsd:enumeration value="No"/> 
				</xsd:restriction> 
			</xsd:simpleType> 
		</xsd:attribute> 
		<xsd:attribute name="type" type="xsd:string" use="required"/> 
	</xsd:complexType> 
	<xsd:complexType name="AddressType"> 
		<xsd:sequence> 
			<xsd:element name="gStreet"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="Street" type="xsd:string" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="POBox" type="xsd:string" minOccurs="0" /> 
			<xsd:element name="City" type="xsd:string"/> 
			<xsd:element name="PostalCode" type="xsd:string"/> 
			<xsd:element name="State" type="xsd:string"/> 
			<xsd:element name="Country" type="xsd:string"/> 
			<xsd:element name="CityCountry" type="xsd:string"/> 
			<xsd:element name="Phones"> 
				<xsd:complexType>   <!-- name="CustomerPhonesType"--> 
					<xsd:sequence> 
						<xsd:element name="Phone" type="custacc:PhoneType" minOccurs="0" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
		</xsd:sequence> 
		<xsd:attribute name="primary" use="required"> 
			<xsd:simpleType> 
				<xsd:restriction base="xsd:NMTOKEN"> 
					<xsd:enumeration value="No"/> 
					<xsd:enumeration value="Yes"/> 
				</xsd:restriction> 
			</xsd:simpleType> 
		</xsd:attribute> 
		<xsd:attribute name="type" type="xsd:string" use="required"/> 
	</xsd:complexType> 
	<xsd:complexType name="EmailType"> 
		<xsd:simpleContent> 
			<xsd:extension base="xsd:string"> 
				<xsd:attribute name="primary" use="required"> 
					<xsd:simpleType> 
						<xsd:restriction base="xsd:NMTOKEN"> 
							<xsd:enumeration value="No"/> 
							<xsd:enumeration value="Yes"/> 
						</xsd:restriction> 
					</xsd:simpleType> 
				</xsd:attribute> 
			</xsd:extension> 
		</xsd:simpleContent> 
	</xsd:complexType> 
	<xsd:complexType name="AddressesType"> 
		<xsd:sequence> 
			<xsd:element name="Address" type="custacc:AddressType"  minOccurs="0" maxOccurs="unbounded" /> 
			<xsd:element name="EmailAddresses" minOccurs="0"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="Email" type="custacc:EmailType"  minOccurs="0" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
		</xsd:sequence> 
	</xsd:complexType> 
	<xsd:simpleType name="PremiumCustomerType"> 
		<xsd:restriction base="xsd:NMTOKEN"> 
			<xsd:enumeration value="Yes"/> 
			<xsd:enumeration value="No"/> 
		</xsd:restriction> 
	</xsd:simpleType> 
	<xsd:simpleType name="CustomerStatusType"> 
		<xsd:restriction base="xsd:NMTOKEN"> 
			<xsd:enumeration value="Active"/> 
			<xsd:enumeration value="Inactive"/> 
		</xsd:restriction> 
	</xsd:simpleType> 



	
	
	<xsd:complexType name="EncryptedType" mixed="false">
	    <xsd:sequence>
	      <xsd:element ref="custacc:CipherData"/> 
	    </xsd:sequence>
	    <xsd:attribute name='Type' type='xsd:anyURI' use='optional'/>
	</xsd:complexType>

	<xsd:element name="CipherData" type="custacc:CipherDataType" /> 

	<xsd:complexType name="CipherDataType" mixed="false">
	  <xsd:sequence>
		<xsd:element name="CipherValue" type="xsd:base64Binary" /> 
	  </xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="OnlineType"> 
		<xsd:sequence> 
			<xsd:element name="Login" type="xsd:string"/> 
			<xsd:element name="Pin"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="EncryptedData" type="custacc:EncryptedType"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="Trading-password"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="EncryptedData" type="custacc:EncryptedType"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
		</xsd:sequence> 
	</xsd:complexType> 
	<xsd:complexType name="TaxType"> 
		<xsd:sequence> 
			<xsd:element name="TaxID" type="xsd:string"  minOccurs="0"/> 
			<xsd:element name="SSN" minOccurs="0"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="EncryptedData" type="custacc:EncryptedType"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="TaxRate" type="xsd:decimal"/> 
		</xsd:sequence> 
	</xsd:complexType> 
	<xsd:complexType name="BankingInfoType"> 
		<xsd:sequence> 
			<xsd:element name="CustomerSince" type="xsd:date"/> 
			<xsd:element name="PremiumCustomer" type="custacc:PremiumCustomerType"/> 
			<xsd:element name="CustomerStatus" type="custacc:CustomerStatusType"/> 
			<xsd:element name="LastContactDate" type="xsd:date"/> 
			<xsd:element name="ReviewFrequency" type="xsd:string"/> 
			<xsd:element name="Online" type="custacc:OnlineType"/> 
			<xsd:element name="Tax" type="custacc:TaxType"/> 
			<xsd:element name="Currency" type="xsd:string"/> 
		</xsd:sequence> 
	</xsd:complexType> 
	<xsd:complexType name="NameType"> 
		<xsd:sequence> 
			<xsd:element name="Title" type="xsd:string" minOccurs="0" /> 
			<xsd:element name="FirstName" type="xsd:string"/> 
			<xsd:element name="MiddleName" type="xsd:string" minOccurs="0" maxOccurs="10"/> 
			<xsd:element name="LastName" type="xsd:string"/> 
			<xsd:element name="Suffix" type="xsd:string" minOccurs="0" /> 
		</xsd:sequence> 
	</xsd:complexType> 
	<xsd:simpleType name="GenderType"> 
		<xsd:restriction base="xsd:NMTOKEN"> 
			<xsd:enumeration value="Male"/> 
			<xsd:enumeration value="Female"/> 
		</xsd:restriction> 
	</xsd:simpleType> 
	<xsd:complexType name="BalanceType"> 
		<xsd:sequence> 
			<xsd:element name="OnlineActualBal" type="xsd:decimal"/> 
			<xsd:element name="OnlineClearedBal" type="xsd:decimal"/> 
			<xsd:element name="WorkingBalance" type="xsd:decimal"/> 
		</xsd:sequence> 
	</xsd:complexType> 
	<xsd:simpleType name="PassbookType"> 
		<xsd:restriction base="xsd:NMTOKEN"> 
			<xsd:enumeration value="Yes"/> 
			<xsd:enumeration value="No"/> 
		</xsd:restriction> 
	</xsd:simpleType> 
	<xsd:complexType name="mValueDateType"> 
		<xsd:sequence> 
			<xsd:element name="ValueDate" type="xsd:date"/> 
			<xsd:element name="CreditMovement" type="xsd:decimal"/> 
			<xsd:element name="ValueDatedBal" type="xsd:decimal"/> 
		</xsd:sequence> 
		<!-- REMOVED xsd:attribute name="m" type="xsd:integer" use="required"/--> 
	</xsd:complexType> 
	<xsd:simpleType name="AllowNettingType"> 
		<xsd:restriction base="xsd:NMTOKEN"> 
			<xsd:enumeration value="Yes"/> 
			<xsd:enumeration value="No"/> 
		</xsd:restriction> 
	</xsd:simpleType> 
	<xsd:complexType name="InputterType"> 
		<xsd:simpleContent> 
			<xsd:extension base="xsd:string"> 
				<xsd:attribute name="c" type="xsd:decimal" use="optional"/> 
			</xsd:extension> 
		</xsd:simpleContent> 
	</xsd:complexType> 
	<xsd:complexType name="PositionType"> 
		<xsd:sequence> 
			<xsd:element name="Symbol" type="xsd:string"/> 
			<xsd:element name="Name" type="xsd:string"/> 
			<xsd:element name="Type" type="xsd:string"/> 
			<xsd:element name="Quantity" type="xsd:decimal"/> 
		</xsd:sequence> 
		<!-- REMOVED xsd:attribute name="id" type="xsd:integer" use="required"/--> 
	</xsd:complexType> 
	<xsd:complexType name="AccountType"> 
		<xsd:sequence> 
			<xsd:element name="Category" type="xsd:string"/> 
			<xsd:element name="AccountTitle" type="xsd:string"/> 
			<xsd:element name="ShortTitle" type="xsd:string"/> 
			<xsd:element name="Mnemonic" type="xsd:string"/> 
			<xsd:element name="Currency" type="xsd:string"/> 
			<xsd:element name="CurrencyMarket" type="xsd:string"/> 
			<xsd:element name="OpeningDate" type="xsd:date"/> 
			<xsd:element name="AccountOfficer" type="xsd:string"/> 
			<xsd:element name="LastUpdate" type="xsd:dateTime"/> 
			<xsd:element name="Balance" type="custacc:BalanceType"/> 
			<xsd:element name="Passbook" type="custacc:PassbookType"/> 
			<xsd:element name="gValueDate"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="mValueDate" type="custacc:mValueDateType" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="ChargeCcy" type="xsd:string"/> 
			<xsd:element name="InterestCcy" type="xsd:string"/> 
			<xsd:element name="AllowNetting" type="custacc:AllowNettingType"/> 
			<xsd:element name="gInputter"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="Inputter" type="custacc:InputterType" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="Holdings"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="Position" type="custacc:PositionType" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
		</xsd:sequence> 
		<xsd:attribute name="id" type="xsd:string" use="required"/> 
	</xsd:complexType> 
	<xsd:complexType name="CustomerType"> 
		<xsd:sequence> 
			<xsd:element name="Mnemonic" type="xsd:string"/> 
			<xsd:element name="ShortNames"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="ShortName" type="xsd:string" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="Name" type="custacc:NameType"/> 
			<xsd:element name="DateOfBirth" type="xsd:date"/> 
			<xsd:element name="Gender" type="custacc:GenderType"/> 
			<xsd:element name="Nationality" type="xsd:string"/> 
			<xsd:element name="CountryOfResidence" type="xsd:string"/> 
			<xsd:element name="Languages"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="Language" type="xsd:string" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="Addresses" type="custacc:AddressesType"/> 
			<xsd:element name="BankingInfo" type="custacc:BankingInfoType"/> 
			<xsd:element name="Accounts"> 
				<xsd:complexType> 
					<xsd:sequence> 
						<xsd:element name="Account" type="custacc:AccountType" maxOccurs="unbounded"/> 
					</xsd:sequence> 
				</xsd:complexType> 
			</xsd:element> 
		</xsd:sequence> 
		<xsd:attribute name="id" type="xsd:integer" use="required"/> 
	</xsd:complexType> 
	<xsd:element name="Customer" type="custacc:CustomerType"/> 
</xsd:schema>

=== dctdevelopment/bagri/etc/samples/tpox/custacc.xml
<?xml version="1.0" encoding="US-ASCII"?>
<Customer id="1011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://tpox-benchmark.com/custacc" xsi:schemaLocation="http://tpox-benchmark.com/custacc custacc.xsd">
	<Mnemonic>VilloldoMarjo</Mnemonic>
	<ShortNames>
		<ShortName>Marjo Villoldo</ShortName>
	</ShortNames>
	<Name>
		<Title>Mrs</Title>
		<FirstName>Marjo</FirstName>
		<MiddleName>Akos</MiddleName>
		<LastName>Villoldo</LastName>
	</Name>
	<DateOfBirth>1956-11-27</DateOfBirth>
	<Gender>Male</Gender>
	<Nationality>Portuguese</Nationality>
	<CountryOfResidence>Portugal</CountryOfResidence>
	<Languages>
		<Language>Portuguese</Language>
	</Languages>
	<Addresses>
		<Address primary="Yes" type="Temporary">
			<gStreet>
				<Street>832 Blossom Hill Rd</Street>
			</gStreet>
			<POBox>51306</POBox>
			<City>San Jose</City>
			<PostalCode>56137</PostalCode>
			<State>California</State>
			<Country>USA</Country>
			<CityCountry>San Jose 56137, USA</CityCountry>
			<Phones>
				<Phone primary="Yes" type="Temporary">
					<CountryCode>196</CountryCode>
					<AreaCode>248</AreaCode>
					<Number>4744196</Number>
				</Phone>
				<Phone primary="No" type="Home">
					<CountryCode>118</CountryCode>
					<AreaCode>900</AreaCode>
					<Number>9123188</Number>
					<Extension>9754</Extension>
				</Phone>
				<Phone primary="No" type="Work">
					<CountryCode>168</CountryCode>
					<AreaCode>684</AreaCode>
					<Number>5958607</Number>
					<Extension>7206</Extension>
				</Phone>
			</Phones>
		</Address>
		<EmailAddresses>
			<Email primary="Yes">Marjo.Villoldo@evergreen.edu</Email>
			<Email primary="No">Fosca.Palomar@co.in</Email>
		</EmailAddresses>
	</Addresses>
	<BankingInfo>
		<CustomerSince>1991-07-22</CustomerSince>
		<PremiumCustomer>No</PremiumCustomer>
		<CustomerStatus>Active</CustomerStatus>
		<LastContactDate>1996-06-27</LastContactDate>
		<ReviewFrequency>Monthly</ReviewFrequency>
		<Online>
			<Login>OVilloldo</Login>
			<Pin>
				<EncryptedData Type="http://www.w3.org/2001/04/xmlenc#Content">
					<CipherData>
						<CipherValue>oZaTDiJHvi71vUhaX8dz</CipherValue>
					</CipherData>
				</EncryptedData>
			</Pin>
			<Trading-password>
				<EncryptedData Type="http://www.w3.org/2001/04/xmlenc#Content">
					<CipherData>
						<CipherValue>ErKP3OfFSGcinasZSFRM</CipherValue>
					</CipherData>
				</EncryptedData>
			</Trading-password>
		</Online>
		<Tax>
			<SSN>
				<EncryptedData Type="http://www.w3.org/2001/04/xmlenc#Content">
					<CipherData>
						<CipherValue>0UJVOB6pnM8RHnfZihcE</CipherValue>
					</CipherData>
				</EncryptedData>
			</SSN>
			<TaxRate>0.34</TaxRate>
		</Tax>
		<Currency>YEN</Currency>
	</BankingInfo>
	<Accounts>
		<!--Account id="104144118" -->
		<Account id="104139870">
			<Category>12</Category>
			<AccountTitle>Mrs Marjo Villoldo EUR</AccountTitle>
			<ShortTitle>Villoldo EUR</ShortTitle>
			<Mnemonic>VilloldoEUR</Mnemonic>
			<Currency>EUR</Currency>
			<CurrencyMarket>3</CurrencyMarket>
			<OpeningDate>2000-07-17</OpeningDate>
			<AccountOfficer>Sissel Kell</AccountOfficer>
			<LastUpdate>2003-08-25T18:04:22</LastUpdate>
			<Balance>
				<OnlineActualBal>448484</OnlineActualBal>
				<OnlineClearedBal>568712</OnlineClearedBal>
				<WorkingBalance>969702</WorkingBalance>
			</Balance>
			<Passbook>Yes</Passbook>
			<gValueDate>
				<mValueDate>
					<ValueDate>1999-02-04</ValueDate>
					<CreditMovement>95261.34</CreditMovement>
					<ValueDatedBal>786528</ValueDatedBal>
				</mValueDate>
				<mValueDate>
					<ValueDate>1995-10-24</ValueDate>
					<CreditMovement>90802.26</CreditMovement>
					<ValueDatedBal>900904</ValueDatedBal>
				</mValueDate>
				<mValueDate>
					<ValueDate>1991-11-01</ValueDate>
					<CreditMovement>55020.97</CreditMovement>
					<ValueDatedBal>578638</ValueDatedBal>
				</mValueDate>
				<mValueDate>
					<ValueDate>1990-09-30</ValueDate>
					<CreditMovement>7557.34</CreditMovement>
					<ValueDatedBal>410335</ValueDatedBal>
				</mValueDate>
				<mValueDate>
					<ValueDate>2002-01-10</ValueDate>
					<CreditMovement>85217.47</CreditMovement>
					<ValueDatedBal>485080</ValueDatedBal>
				</mValueDate>
			</gValueDate>
			<ChargeCcy>EUR</ChargeCcy>
			<InterestCcy>EUR</InterestCcy>
			<AllowNetting>Yes</AllowNetting>
			<gInputter>
				<Inputter>Gareth Vittorini</Inputter>
				<Inputter>Parker Tawa</Inputter>
				<Inputter>Gongzhu Clemm</Inputter>
				<Inputter>Gareth Vittorini</Inputter>
				<Inputter>Gareth Vittorini</Inputter>
			</gInputter>
			<Holdings>
				<!--Position>
					<Symbol>PRRR</Symbol>
					<Name>Pioneer Railcorp</Name>
					<Type>Stock</Type>
					<Quantity>1816.780</Quantity>
				</Position>
				<Position>
					<Symbol>PHYDX</Symbol>
					<Name>PIMCO High Yield D</Name>
					<Type>Bond Fund</Type>
					<Quantity>734.599</Quantity>
				</Position>
				<Position>
					<Symbol>AIIIX</Symbol>
					<Name>American AAdvantage Intl Eq Idx Inst</Name>
					<Type>Stock Fund</Type>
					<Quantity>2330.892</Quantity>
				</Position-->
				<Position>
					<Symbol>IBM</Symbol>
					<Name>Internatinal Business Machines Corporation</Name>
					<Type>Stock</Type>
					<Quantity>1916.780</Quantity>
				</Position>
				<Position>
					<Symbol>PTTAX</Symbol>
					<Name>PIMCO Total Return A</Name>
					<Type>Bond Fund</Type>
					<Quantity>2734.599</Quantity>
				</Position>
				<Position>
					<Symbol>VFINX</Symbol>
					<Name>Vanguard 500 Index Fund</Name>
					<Type>Stock Fund</Type>
					<Quantity>3250.892</Quantity>
				</Position>
			</Holdings>
		</Account>
	</Accounts>
</Customer>
