=== dctdevelopment/bagri/etc/samples/tpox/security.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://tpox-benchmark.com/security" xmlns:security="http://tpox-benchmark.com/security" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:simpleType name="SecurityDecimalType">
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0"/>
			<xsd:totalDigits value="13"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Price52weekType">
		<xsd:sequence>
			<xsd:element name="Price52week-low" type="security:SecurityDecimalType"/>
			<xsd:element name="Price52week-low-date" type="xsd:date"/>
			<xsd:element name="Price52week-high" type="security:SecurityDecimalType"/>
			<xsd:element name="Price52week-high-date" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PriceTodayType">
		<xsd:all>
			<xsd:element name="PreviousClose" type="security:SecurityDecimalType"/>
			<xsd:element name="Open" type="security:SecurityDecimalType"/>
			<xsd:element name="High" type="security:SecurityDecimalType"/>
			<xsd:element name="Low" type="security:SecurityDecimalType"/>
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="PriceType">
		<xsd:sequence>
			<xsd:element name="LastTrade" type="security:SecurityDecimalType"/>
			<xsd:element name="Ask" type="security:SecurityDecimalType"/>
			<xsd:element name="Bid" type="security:SecurityDecimalType"/>
			<xsd:element name="Price50DayAvg" type="security:SecurityDecimalType"/>
			<xsd:element name="Price200DayAvg" type="security:SecurityDecimalType"/>
			<xsd:element name="PriceToday" type="security:PriceTodayType"/>
			<xsd:element name="Price52week" type="security:Price52weekType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="SecurityInfoType">
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name="StockInformation">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Sector" type="security:SectorType"/>
							<xsd:element name="Industry" type="security:IndustryType" minOccurs="0" maxOccurs="unbounded"/>
							<xsd:element name="Category" type="security:CategoryType"/>
							<xsd:element name="OutstShares" type="security:SecurityDecimalType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="FundInformation">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="FundFamily" type="xsd:string" minOccurs="1" maxOccurs="1"/>
							<xsd:element name="Sector" type="security:SectorType" minOccurs="0"/>
							<xsd:element name="Industry" type="security:IndustryType" minOccurs="0" maxOccurs="unbounded"/>
							<xsd:element name="AssetGroup" type="xsd:string"/>
							<!--xsd:choice-->
							<xsd:element name="Category" type="security:CategoryType" minOccurs="0"/>
							<xsd:element name="FixedIncome" type="security:FixedIncomeType" minOccurs="0"/>
							<!--/xsd:choice-->
							<xsd:element name="ExpenseRatio" type="security:SecurityDecimalType"/>
							<xsd:element name="TotalAssets" type="security:SecurityDecimalType"/>
							<xsd:element name="MinInitialInvestment" type="xsd:integer" minOccurs="0"/>
							<xsd:element name="MinSubsequentInvestment" type="xsd:integer" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="Description" type="security:DescriptionType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="Security">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Symbol">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="7"/>
							<xsd:minLength value="1"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="Name" type="xsd:string"/>
				<xsd:element name="ShortName" type="xsd:string"/>
				<xsd:element name="SecurityType">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="Stock"/>
							<xsd:enumeration value="Bond"/>
							<xsd:enumeration value="Stock Fund"/>
							<xsd:enumeration value="Bond Fund"/>
							<xsd:enumeration value="Mixed Fund"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="SecurityInformation" type="security:SecurityInfoType"/>
				<xsd:element name="Price" type="security:PriceType"/>
				<xsd:element name="PE" type="security:SecurityDecimalType"/>
				<xsd:element name="Yield" type="security:SecurityDecimalType"/>
				<xsd:element name="DivPerShare" type="security:SecurityDecimalType"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:integer" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!-- #############  Security Information ######################### -->
	<xsd:complexType name="CategoryType">
		<xsd:attribute name="Capitalization" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Large"/>
					<xsd:enumeration value="Medium"/>
					<xsd:enumeration value="Small"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="Class" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Value"/>
					<xsd:enumeration value="Growth"/>
					<xsd:enumeration value="Blend"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="FixedIncomeType">
		<xsd:attribute name="Duration" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Short Term"/>
					<xsd:enumeration value="Medium Term"/>
					<xsd:enumeration value="Long Term"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="Quality" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="High"/>
					<xsd:enumeration value="Medium"/>
					<xsd:enumeration value="Low"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:element name="AnyKeyword" type="xsd:string" abstract="true"/>
	<xsd:element name="CEO" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Product" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Competitor" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Assets" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Rating" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Manager" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Risk" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Cost" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Dividend" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Strategy" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Holdings" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Index" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Keyword" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:complexType name="TextWithKeywordsType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="security:AnyKeyword" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="DescriptionType">
		<xsd:choice>
			<xsd:element name="BusinessSummary" type="security:TextWithKeywordsType" minOccurs="0"/>
			<xsd:sequence>
				<xsd:element name="FundDescription" type="security:TextWithKeywordsType"/>
				<xsd:element name="Management" type="security:TextWithKeywordsType" minOccurs="0"/>
			</xsd:sequence>
		</xsd:choice>
	</xsd:complexType>
	<xsd:simpleType name="SectorType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Basic Materials"/>
			<xsd:enumeration value="Capital Goods"/>
			<xsd:enumeration value="Conglomerates"/>
			<xsd:enumeration value="Consumer Cyclical"/>
			<xsd:enumeration value="Consumer Non-Cyclical"/>
			<xsd:enumeration value="Energy"/>
			<xsd:enumeration value="Financial"/>
			<xsd:enumeration value="Healthcare"/>
			<xsd:enumeration value="Services"/>
			<xsd:enumeration value="Technology"/>
			<xsd:enumeration value="Transportation"/>
			<xsd:enumeration value="Utilities"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IndustryType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Apparel/Accessories"/>
			<xsd:enumeration value="AirCourier"/>
			<xsd:enumeration value="Aerospace&amp;Defense"/>
			<xsd:enumeration value="Advertising"/>
			<xsd:enumeration value="Auto&amp;TruckManufacturers"/>
			<xsd:enumeration value="Auto&amp;TruckParts"/>
			<xsd:enumeration value="Airline"/>
			<xsd:enumeration value="Appliance&amp;Tool"/>
			<xsd:enumeration value="Audio&amp;VideoEquipment"/>
			<xsd:enumeration value="Beverages(Alcoholic)"/>
			<xsd:enumeration value="Broadcasting&amp;CableTV"/>
			<xsd:enumeration value="Biotechnology&amp;Drugs"/>
			<xsd:enumeration value="Beverages(Non-Alcoholic)"/>
			<xsd:enumeration value="BusinessServices"/>
			<xsd:enumeration value="Constr.&amp;Agric.Machinery"/>
			<xsd:enumeration value="Chemicals-Plastics&amp;Rubber"/>
			<xsd:enumeration value="ComputerStorageDevices"/>
			<xsd:enumeration value="CommunicationsEquipment"/>
			<xsd:enumeration value="ConsumerFinancialServices"/>
			<xsd:enumeration value="Casinos&amp;Gaming"/>
			<xsd:enumeration value="ComputerHardware"/>
			<xsd:enumeration value="Containers&amp;Packaging"/>
			<xsd:enumeration value="Coal"/>
			<xsd:enumeration value="ChemicalManufacturing"/>
			<xsd:enumeration value="ComputerNetworks"/>
			<xsd:enumeration value="Conglomerates"/>
			<xsd:enumeration value="ComputerPeripherals"/>
			<xsd:enumeration value="Crops"/>
			<xsd:enumeration value="ComputerServices"/>
			<xsd:enumeration value="Retail(Catalog&amp;MailOrder)"/>
			<xsd:enumeration value="CommunicationsServices"/>
			<xsd:enumeration value="ConstructionServices"/>
			<xsd:enumeration value="Constr.-Supplies&amp;Fixtures"/>
			<xsd:enumeration value="Retail(Department&amp;Discount)"/>
			<xsd:enumeration value="Retail(Drugs)"/>
			<xsd:enumeration value="ElectronicInstruments&amp;Controls"/>
			<xsd:enumeration value="ElectricUtilities"/>
			<xsd:enumeration value="Furniture&amp;Fixtures"/>
			<xsd:enumeration value="Fish/Livestock"/>
			<xsd:enumeration value="Footwear"/>
			<xsd:enumeration value="FoodProcessing"/>
			<xsd:enumeration value="FabricatedPlastic&amp;Rubber"/>
			<xsd:enumeration value="Forestry&amp;WoodProducts"/>
			<xsd:enumeration value="Retail(Grocery)"/>
			<xsd:enumeration value="Gold&amp;Silver"/>
			<xsd:enumeration value="HealthcareFacilities"/>
			<xsd:enumeration value="Retail(HomeImprovement)"/>
			<xsd:enumeration value="Hotels&amp;Motels"/>
			<xsd:enumeration value="Insurance(Accident&amp;Health)"/>
			<xsd:enumeration value="Insurance(Life)"/>
			<xsd:enumeration value="Insurance(Miscellaneous)"/>
			<xsd:enumeration value="Insurance(Prop&amp;Casualty)"/>
			<xsd:enumeration value="Iron&amp;Steel"/>
			<xsd:enumeration value="InvestmentServices"/>
			<xsd:enumeration value="Jewelry&amp;Silverware"/>
			<xsd:enumeration value="MoneyCenterBanks"/>
			<xsd:enumeration value="MajorDrugs"/>
			<xsd:enumeration value="MedicalEquipment&amp;Supplies"/>
			<xsd:enumeration value="Misc.FabricatedProducts"/>
			<xsd:enumeration value="Misc.CapitalGoods"/>
			<xsd:enumeration value="MobileHomes&amp;RVs"/>
			<xsd:enumeration value="MetalMining"/>
			<xsd:enumeration value="MotionPictures"/>
			<xsd:enumeration value="Misc.FinancialServices"/>
			<xsd:enumeration value="Misc.Transportation"/>
			<xsd:enumeration value="NaturalGasUtilities"/>
			<xsd:enumeration value="Non-MetallicMining"/>
			<xsd:enumeration value="OfficeEquipment"/>
			<xsd:enumeration value="Oil&amp;Gas-Integrated"/>
			<xsd:enumeration value="Oil&amp;GasOperations"/>
			<xsd:enumeration value="OfficeSupplies"/>
			<xsd:enumeration value="OilWellServices&amp;Equipment"/>
			<xsd:enumeration value="Paper&amp;PaperProducts"/>
			<xsd:enumeration value="Photography"/>
			<xsd:enumeration value="Personal&amp;HouseholdProducts"/>
			<xsd:enumeration value="Printing&amp;Publishing"/>
			<xsd:enumeration value="PrintingServices"/>
			<xsd:enumeration value="PersonalServices"/>
			<xsd:enumeration value="RecreationalActivities"/>
			<xsd:enumeration value="RegionalBanks"/>
			<xsd:enumeration value="RealEstateOperations"/>
			<xsd:enumeration value="Retail(Speciality)"/>
			<xsd:enumeration value="Construction-RawMaterials"/>
			<xsd:enumeration value="Rental&amp;Leasing"/>
			<xsd:enumeration value="RecreationalProducts"/>
			<xsd:enumeration value="Railroads"/>
			<xsd:enumeration value="Restaurants"/>
			<xsd:enumeration value="Retail(Apparel)"/>
			<xsd:enumeration value="S&amp;Ls/SavingsBanks"/>
			<xsd:enumeration value="Schools"/>
			<xsd:enumeration value="Semiconductors"/>
			<xsd:enumeration value="Software&amp;Programming"/>
			<xsd:enumeration value="SecuritySystems&amp;Services"/>
			<xsd:enumeration value="Scientific&amp;TechnicalInstr."/>
			<xsd:enumeration value="Retail(Technology)"/>
			<xsd:enumeration value="Tires"/>
			<xsd:enumeration value="Textiles-NonApparel"/>
			<xsd:enumeration value="Tobacco"/>
			<xsd:enumeration value="Trucking"/>
			<xsd:enumeration value="WasteManagementServices"/>
			<xsd:enumeration value="WaterTransportation"/>
			<xsd:enumeration value="WaterUtilities"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== dctdevelopment/bagri/bagri-distr/src/main/data/tpox/security29674.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- generated by ToXgene Version 2.3 on Thu Jun 07 16:17:45 EDT 2007 -->
<Security id="29674" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://tpox-benchmark.com/security"
    xsi:schemaLocation="http://tpox-benchmark.com/security security.xsd">
    <Symbol>PRDGX</Symbol>
    <Name>T. Rowe Price Dividend Growth</Name>
    <ShortName>PRDGX</ShortName>
    <SecurityType>Stock Fund</SecurityType>
    <SecurityInformation>
        <FundInformation>
            <FundFamily>T. Rowe Price</FundFamily>
            <Industry>Software&amp;Programming</Industry>
            <Industry>OilWellServices&amp;Equipment</Industry>
            <Industry>Retail(Apparel)</Industry>
            <Industry>Insurance(Life)</Industry>
            <Industry>Paper&amp;PaperProducts</Industry>
            <Industry>Retail(Drugs)</Industry>
            <AssetGroup>Large Value</AssetGroup>
            <Category Capitalization="Medium" Class="Value"/>
            <ExpenseRatio>0.16</ExpenseRatio>
            <TotalAssets>64691363840</TotalAssets>
            <MinInitialInvestment>3000</MinInitialInvestment>
            <MinSubsequentInvestment>100</MinSubsequentInvestment>
        </FundInformation>
        <Description>
            <FundDescription>dolphins among the foxes promise evenly close, quiet warhorses;decoys
                would lose quietly except the frays?finally busy realms over the careful grouches
                hang except the evenly furious foxes?final hockey atop the quick instructions may
                mold in place of the multipliers?permanent dolphins according to the idly ruthless
                dolphins can eat under the careful orbits:ironically even asymptotes would affix
                slow, thin pinto;pearls besides the ruthless hockey try to snooze always atop the
                blithely final beans?courts could grow quickl<Risk>closely quick dependencies</Risk>
                silently brave grouches among the decoys detect throughout the fluffy
                instructions.ironic orbits try to kindle at the silently stealthy
                escapades;regularly final sentiments will hang.quickly permanent excuses print
                instead of the even pearls.grouches will maintain outside the even, brave
                frays;permanent, idle Tiresias at the fluffy theodolites affix sly somas--quiet,
                fluffy theodoeven, enticing ideas breach busily:somas poach.careful, idle sentiments
                mold warthogs.silent multipliers past the finally slow excuses shall have to impress
                fluffily fluffily sly sauternes;enticing, fluffy Tiresias atop the finally furious
                tithes must impress enticingly decoys!courts run busy realms;permanent, ironic
                grouches sublate slowly of the carefully bold decoys;quiet, ironic warthogs haggle
                sometimes orbits.final hockey sublate?busily bold orbits shall integrate
                regularly!daring instructions ought <CEO>frays ought to solve attainments</CEO>
                carefully blithe beans should have to solve idly behind the foxes?attainments need
                to promise thinly ruthless, permanent escapades.regularly ironic sheaves across the
                silently stealthy escapades shall have to detect furiously with the slow, brave
                sentiments!permanent grouches will mold since the furious excuses?fluffy, thin frays
                except the bravely final warthogs x-ray finally throughout the stealthly final
                epitaphs.quick, silent
                s<Holdings>permanent, stealthy grouches along the ironic, q</Holdings> dogged,
                furious notornis shall have to lose bravely never fluffy grouches:furious foxes will
                have to snooze busily?fluffy courts thrash?enticing, ruthless tithes among the
                stealthy, quiet pearls sleep slyly sly sauternes;enticingly
                permanen<Keyword>blithe sauternes should</Keyword> depths will have to serve quickly
                permanent, ironic warhorses:quick, idle courts should have to unwind according to
                the closely even orbits.regularly slow patterns lose enticingly sly foxes--always
                sly pinto could use sometimes bravely regular orbits;Tiresias up the permanent, sly
                excuses sublate blithely through the sly, slow warthogs?brave, brave players
                haggle;fluffy pearls alongside of the even sheaves should haggle beans:closely
                bol</FundDescription>
            <Management>stealthly regular decoys should impress since the brave, idle
                multipliers!instructions should have to solve blithely fluffy gifts?sometimes
                regular platelets lose thinly since the even sentiments:busily dogged notornis must
                have to snooze--pinto play thinly--courts affix tithes:quiet multipliers should have
                to wake busily for the quickly ironic Tiresias!fluffy sentiments may haggle?busy
                dugouts from the never brave pearls grow ironic, bold escapades--furious pinto over
                the permanent theodolites should have to kindle quiet, daring sheaves--careful,
                dogged pains can detect.idle foxes can haggle daring<Risk>forges from t</Risk> sly
                epitaphs of the always furious escapades will have to doze escapades!even hockey
                doubt--furious pinto over the sometimes dogged grouches print into the thinly quick
                players!quick epitaphs above the frays affix quickly despite the multipliers--forges
                into the enticing pains play past the careful, stealthy players?grouches may hinder
                bravely quiet dependencies.enticing pearls above the dependencies do serve busily
                stealthly busy realms.idl<Keyword>regular patterns sleep silently blithe</Keyword>
                quick, daring players might promise atop the even tithes:slowly regular decoys can
                dazzle closely.quick players try to snooze doggedly above the busy escapades?even
                frays near the busily furious foxes sleep regularly to the furious foxes;asymptotes
                through the final realms nod epitaphs--enticingly fluffy tithes may integrate
                quietly busy notornis?pinto are ironically;carefully stealthy excuses around the
                busy, thin foxes poach ironically idly quick grouches!thin hockey can grow during
                the dogged dolphins;regularly permanent
                epi<Strategy>never silent gifts could cajole i</Strategy> sentiments affix inside
                the permanent, idle escapades.furious orbits cajole always--braids belive regularly
                sly, sly somas:slow, even dependencies sleep around the boldly close
                epitaphs:stealthy, daring theodolites must have to eat.thinly quick escapades before
                the evenly daring dolphins integrate stealthy platelets:final, quiet orbits must
                run:s<Competitor>sauternes on the asymptotes woul</Competitor> theodolites need to
                sublate furiously ironically close frets;quiet, thin foxes atop the enticingly
                fluffy pains nag ruthless gifts;bold, daring gifts can solve furiously!slow gifts
                can affix above the permanently stealthy sentiments:final foxes nag slowly permanent
                orbits;asymptotes over the blithe dinos was evenly with the quick courts--stealthy,
                thin decoys beneath the sly, thin frets dazzle brave, furious grouches!sly, even
                Tiresias unwind from the quick, ruthless multipliers;blithe, blithe excuses should
                have to x-ray!fruthless Tiresias haggle enticingly sheaves;regular frets beyond the
                brave, dogged epitaphs can wake finally under the permanent, furious
                multipliers.orbits need to snooze with the bravely blithe platelets;beans cajole
                before the dinos--quiet, regul</Management>
        </Description>
    </SecurityInformation>
    <Price>
        <LastTrade>36.4325</LastTrade>
        <Ask>36.5506</Ask>
        <Bid>36.2165</Bid>
        <Price50DayAvg>37.4594</Price50DayAvg>
        <Price200DayAvg>40.5779</Price200DayAvg>
        <PriceToday>
            <PreviousClose>36.4325</PreviousClose>
            <Open>35.9288</Open>
            <High>38.6590</High>
            <Low>35.9069</Low>
        </PriceToday>
        <Price52week>
            <Price52week-low>35.9069</Price52week-low>
            <Price52week-low-date>2004-04-23</Price52week-low-date>
            <Price52week-high>40.5779</Price52week-high>
            <Price52week-high-date>2004-07-21</Price52week-high-date>
        </Price52week>
    </Price>
    <PE>37.38</PE>
    <Yield>3.29</Yield>
    <DivPerShare>1.04</DivPerShare>
</Security>
