=== dctdevelopment/bagri/etc/samples/tpox/security.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://tpox-benchmark.com/security" xmlns:security="http://tpox-benchmark.com/security" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:simpleType name="SecurityDecimalType">
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0"/>
			<xsd:totalDigits value="13"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Price52weekType">
		<xsd:sequence>
			<xsd:element name="Price52week-low" type="security:SecurityDecimalType"/>
			<xsd:element name="Price52week-low-date" type="xsd:date"/>
			<xsd:element name="Price52week-high" type="security:SecurityDecimalType"/>
			<xsd:element name="Price52week-high-date" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PriceTodayType">
		<xsd:all>
			<xsd:element name="PreviousClose" type="security:SecurityDecimalType"/>
			<xsd:element name="Open" type="security:SecurityDecimalType"/>
			<xsd:element name="High" type="security:SecurityDecimalType"/>
			<xsd:element name="Low" type="security:SecurityDecimalType"/>
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="PriceType">
		<xsd:sequence>
			<xsd:element name="LastTrade" type="security:SecurityDecimalType"/>
			<xsd:element name="Ask" type="security:SecurityDecimalType"/>
			<xsd:element name="Bid" type="security:SecurityDecimalType"/>
			<xsd:element name="Price50DayAvg" type="security:SecurityDecimalType"/>
			<xsd:element name="Price200DayAvg" type="security:SecurityDecimalType"/>
			<xsd:element name="PriceToday" type="security:PriceTodayType"/>
			<xsd:element name="Price52week" type="security:Price52weekType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="SecurityInfoType">
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name="StockInformation">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Sector" type="security:SectorType"/>
							<xsd:element name="Industry" type="security:IndustryType" minOccurs="0" maxOccurs="unbounded"/>
							<xsd:element name="Category" type="security:CategoryType"/>
							<xsd:element name="OutstShares" type="security:SecurityDecimalType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="FundInformation">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="FundFamily" type="xsd:string" minOccurs="1" maxOccurs="1"/>
							<xsd:element name="Sector" type="security:SectorType" minOccurs="0"/>
							<xsd:element name="Industry" type="security:IndustryType" minOccurs="0" maxOccurs="unbounded"/>
							<xsd:element name="AssetGroup" type="xsd:string"/>
							<!--xsd:choice-->
							<xsd:element name="Category" type="security:CategoryType" minOccurs="0"/>
							<xsd:element name="FixedIncome" type="security:FixedIncomeType" minOccurs="0"/>
							<!--/xsd:choice-->
							<xsd:element name="ExpenseRatio" type="security:SecurityDecimalType"/>
							<xsd:element name="TotalAssets" type="security:SecurityDecimalType"/>
							<xsd:element name="MinInitialInvestment" type="xsd:integer" minOccurs="0"/>
							<xsd:element name="MinSubsequentInvestment" type="xsd:integer" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="Description" type="security:DescriptionType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="Security">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Symbol">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="7"/>
							<xsd:minLength value="1"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="Name" type="xsd:string"/>
				<xsd:element name="ShortName" type="xsd:string"/>
				<xsd:element name="SecurityType">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="Stock"/>
							<xsd:enumeration value="Bond"/>
							<xsd:enumeration value="Stock Fund"/>
							<xsd:enumeration value="Bond Fund"/>
							<xsd:enumeration value="Mixed Fund"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="SecurityInformation" type="security:SecurityInfoType"/>
				<xsd:element name="Price" type="security:PriceType"/>
				<xsd:element name="PE" type="security:SecurityDecimalType"/>
				<xsd:element name="Yield" type="security:SecurityDecimalType"/>
				<xsd:element name="DivPerShare" type="security:SecurityDecimalType"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:integer" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!-- #############  Security Information ######################### -->
	<xsd:complexType name="CategoryType">
		<xsd:attribute name="Capitalization" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Large"/>
					<xsd:enumeration value="Medium"/>
					<xsd:enumeration value="Small"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="Class" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Value"/>
					<xsd:enumeration value="Growth"/>
					<xsd:enumeration value="Blend"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="FixedIncomeType">
		<xsd:attribute name="Duration" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Short Term"/>
					<xsd:enumeration value="Medium Term"/>
					<xsd:enumeration value="Long Term"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="Quality" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="High"/>
					<xsd:enumeration value="Medium"/>
					<xsd:enumeration value="Low"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:element name="AnyKeyword" type="xsd:string" abstract="true"/>
	<xsd:element name="CEO" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Product" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Competitor" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Assets" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Rating" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Manager" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Risk" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Cost" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Dividend" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Strategy" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Holdings" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Index" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:element name="Keyword" type="xsd:string" substitutionGroup="security:AnyKeyword"/>
	<xsd:complexType name="TextWithKeywordsType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="security:AnyKeyword" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="DescriptionType">
		<xsd:choice>
			<xsd:element name="BusinessSummary" type="security:TextWithKeywordsType" minOccurs="0"/>
			<xsd:sequence>
				<xsd:element name="FundDescription" type="security:TextWithKeywordsType"/>
				<xsd:element name="Management" type="security:TextWithKeywordsType" minOccurs="0"/>
			</xsd:sequence>
		</xsd:choice>
	</xsd:complexType>
	<xsd:simpleType name="SectorType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Basic Materials"/>
			<xsd:enumeration value="Capital Goods"/>
			<xsd:enumeration value="Conglomerates"/>
			<xsd:enumeration value="Consumer Cyclical"/>
			<xsd:enumeration value="Consumer Non-Cyclical"/>
			<xsd:enumeration value="Energy"/>
			<xsd:enumeration value="Financial"/>
			<xsd:enumeration value="Healthcare"/>
			<xsd:enumeration value="Services"/>
			<xsd:enumeration value="Technology"/>
			<xsd:enumeration value="Transportation"/>
			<xsd:enumeration value="Utilities"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IndustryType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Apparel/Accessories"/>
			<xsd:enumeration value="AirCourier"/>
			<xsd:enumeration value="Aerospace&amp;Defense"/>
			<xsd:enumeration value="Advertising"/>
			<xsd:enumeration value="Auto&amp;TruckManufacturers"/>
			<xsd:enumeration value="Auto&amp;TruckParts"/>
			<xsd:enumeration value="Airline"/>
			<xsd:enumeration value="Appliance&amp;Tool"/>
			<xsd:enumeration value="Audio&amp;VideoEquipment"/>
			<xsd:enumeration value="Beverages(Alcoholic)"/>
			<xsd:enumeration value="Broadcasting&amp;CableTV"/>
			<xsd:enumeration value="Biotechnology&amp;Drugs"/>
			<xsd:enumeration value="Beverages(Non-Alcoholic)"/>
			<xsd:enumeration value="BusinessServices"/>
			<xsd:enumeration value="Constr.&amp;Agric.Machinery"/>
			<xsd:enumeration value="Chemicals-Plastics&amp;Rubber"/>
			<xsd:enumeration value="ComputerStorageDevices"/>
			<xsd:enumeration value="CommunicationsEquipment"/>
			<xsd:enumeration value="ConsumerFinancialServices"/>
			<xsd:enumeration value="Casinos&amp;Gaming"/>
			<xsd:enumeration value="ComputerHardware"/>
			<xsd:enumeration value="Containers&amp;Packaging"/>
			<xsd:enumeration value="Coal"/>
			<xsd:enumeration value="ChemicalManufacturing"/>
			<xsd:enumeration value="ComputerNetworks"/>
			<xsd:enumeration value="Conglomerates"/>
			<xsd:enumeration value="ComputerPeripherals"/>
			<xsd:enumeration value="Crops"/>
			<xsd:enumeration value="ComputerServices"/>
			<xsd:enumeration value="Retail(Catalog&amp;MailOrder)"/>
			<xsd:enumeration value="CommunicationsServices"/>
			<xsd:enumeration value="ConstructionServices"/>
			<xsd:enumeration value="Constr.-Supplies&amp;Fixtures"/>
			<xsd:enumeration value="Retail(Department&amp;Discount)"/>
			<xsd:enumeration value="Retail(Drugs)"/>
			<xsd:enumeration value="ElectronicInstruments&amp;Controls"/>
			<xsd:enumeration value="ElectricUtilities"/>
			<xsd:enumeration value="Furniture&amp;Fixtures"/>
			<xsd:enumeration value="Fish/Livestock"/>
			<xsd:enumeration value="Footwear"/>
			<xsd:enumeration value="FoodProcessing"/>
			<xsd:enumeration value="FabricatedPlastic&amp;Rubber"/>
			<xsd:enumeration value="Forestry&amp;WoodProducts"/>
			<xsd:enumeration value="Retail(Grocery)"/>
			<xsd:enumeration value="Gold&amp;Silver"/>
			<xsd:enumeration value="HealthcareFacilities"/>
			<xsd:enumeration value="Retail(HomeImprovement)"/>
			<xsd:enumeration value="Hotels&amp;Motels"/>
			<xsd:enumeration value="Insurance(Accident&amp;Health)"/>
			<xsd:enumeration value="Insurance(Life)"/>
			<xsd:enumeration value="Insurance(Miscellaneous)"/>
			<xsd:enumeration value="Insurance(Prop&amp;Casualty)"/>
			<xsd:enumeration value="Iron&amp;Steel"/>
			<xsd:enumeration value="InvestmentServices"/>
			<xsd:enumeration value="Jewelry&amp;Silverware"/>
			<xsd:enumeration value="MoneyCenterBanks"/>
			<xsd:enumeration value="MajorDrugs"/>
			<xsd:enumeration value="MedicalEquipment&amp;Supplies"/>
			<xsd:enumeration value="Misc.FabricatedProducts"/>
			<xsd:enumeration value="Misc.CapitalGoods"/>
			<xsd:enumeration value="MobileHomes&amp;RVs"/>
			<xsd:enumeration value="MetalMining"/>
			<xsd:enumeration value="MotionPictures"/>
			<xsd:enumeration value="Misc.FinancialServices"/>
			<xsd:enumeration value="Misc.Transportation"/>
			<xsd:enumeration value="NaturalGasUtilities"/>
			<xsd:enumeration value="Non-MetallicMining"/>
			<xsd:enumeration value="OfficeEquipment"/>
			<xsd:enumeration value="Oil&amp;Gas-Integrated"/>
			<xsd:enumeration value="Oil&amp;GasOperations"/>
			<xsd:enumeration value="OfficeSupplies"/>
			<xsd:enumeration value="OilWellServices&amp;Equipment"/>
			<xsd:enumeration value="Paper&amp;PaperProducts"/>
			<xsd:enumeration value="Photography"/>
			<xsd:enumeration value="Personal&amp;HouseholdProducts"/>
			<xsd:enumeration value="Printing&amp;Publishing"/>
			<xsd:enumeration value="PrintingServices"/>
			<xsd:enumeration value="PersonalServices"/>
			<xsd:enumeration value="RecreationalActivities"/>
			<xsd:enumeration value="RegionalBanks"/>
			<xsd:enumeration value="RealEstateOperations"/>
			<xsd:enumeration value="Retail(Speciality)"/>
			<xsd:enumeration value="Construction-RawMaterials"/>
			<xsd:enumeration value="Rental&amp;Leasing"/>
			<xsd:enumeration value="RecreationalProducts"/>
			<xsd:enumeration value="Railroads"/>
			<xsd:enumeration value="Restaurants"/>
			<xsd:enumeration value="Retail(Apparel)"/>
			<xsd:enumeration value="S&amp;Ls/SavingsBanks"/>
			<xsd:enumeration value="Schools"/>
			<xsd:enumeration value="Semiconductors"/>
			<xsd:enumeration value="Software&amp;Programming"/>
			<xsd:enumeration value="SecuritySystems&amp;Services"/>
			<xsd:enumeration value="Scientific&amp;TechnicalInstr."/>
			<xsd:enumeration value="Retail(Technology)"/>
			<xsd:enumeration value="Tires"/>
			<xsd:enumeration value="Textiles-NonApparel"/>
			<xsd:enumeration value="Tobacco"/>
			<xsd:enumeration value="Trucking"/>
			<xsd:enumeration value="WasteManagementServices"/>
			<xsd:enumeration value="WaterTransportation"/>
			<xsd:enumeration value="WaterUtilities"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== dctdevelopment/bagri/bagri-distr/src/main/data/tpox/security5621.xml
<?xml version="1.0"?>
<Security id="5621" xmlns="http://tpox-benchmark.com/security"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tpox-benchmark.com/security security.xsd">
	<Symbol>IBM</Symbol>
	<Name>Internatinal Business Machines Corporation</Name>
	<ShortName>IBM</ShortName>
	<SecurityType>Stock</SecurityType>
	<SecurityInformation>
		<StockInformation>
			<Sector>Technology</Sector>
			<Industry>ComputerHardware</Industry>
			<Industry>ComputerServices</Industry>
			<Industry>ComputerStorageDevices</Industry>
			<Industry>Software&amp;Programming</Industry>
			<Industry>Semiconductors</Industry>
			<Category Capitalization="Large" Class="Value"/>
			<OutstShares>165867735</OutstShares>
		</StockInformation>
		<Description>
			<BusinessSummary>
International Business Machines Corporation (IBM) uses advanced information technology (IT) to provide customer solutions. The Company operates primarily in a single industry using several segments that create value by offering a variety of solutions that include, either singularly or in some combination, technologies, systems, products, services, software and financing. Organizationally, its major operations are comprised of a Global Services segment; three hardware product segments, Systems Group, Personal Systems Group and Technology Group; a Software segment; a Global Financing segment, and an Enterprise Investments segment. The segments are determined based on several factors, including customer base, homogeneity of products, technology and delivery channels.
The Company offers its products through its global sales and distribution organizations. The sales and distribution organizations have both a geographic focus (in the Americas, Europe/Middle East/Africa and Asia Pacific) and a specialized and global industry focus. In addition, these organizations include a global sales and distribution effort devoted exclusively to small and medium-sized businesses. IBM also offers its products through a variety of third-party distributors and resellers, as well as through its online channels.
IBM owns, or is licensed under a number of patents, which vary in duration, relating to its products, and its businesses employ a variety of components, supplies and raw materials from a substantial number of suppliers around the world. It operates in more than 160 countries worldwide and derives more than half of its revenues from sales outside the United States. IBM's revenues are affected by such factors as the introduction of new products, the length of the sales cycles and the seasonality of technology purchases.
			</BusinessSummary>
		</Description>
	</SecurityInformation>
	<Price>
		<LastTrade>86.23</LastTrade>
		<Ask>88.12</Ask>
		<Bid>84.78</Bid>
		<Price50DayAvg>85.37</Price50DayAvg>
		<Price200DayAvg>80.21</Price200DayAvg>
		<PriceToday>
			<PreviousClose>86.07</PreviousClose>
			<Open>86.23</Open>
			<Low>86.23</Low>
			<High>86.23</High>
		</PriceToday>
		<Price52week>
			<Price52week-low>69.44</Price52week-low>
			<Price52week-low-date>2002-05-12</Price52week-low-date>
			<Price52week-high>92.11</Price52week-high>
			<Price52week-high-date>2002-11-02</Price52week-high-date>
		</Price52week>
	</Price>
	<PE>27.13</PE>
	<Yield>0.74</Yield>
	<DivPerShare>0.64</DivPerShare>
</Security>

=== dctdevelopment/bagri/etc/samples/tpox/security9012.xml
<?xml version="1.0"?>
<Security id="9012" xmlns="http://tpox-benchmark.com/security"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tpox-benchmark.com/security security.xsd">
	<Symbol>PTTAX</Symbol>
	<Name>PIMCO Total Return A</Name>
	<ShortName>PIMCO TotRet</ShortName>
	<SecurityType>Bond Fund</SecurityType>
	<SecurityInformation>
		<FundInformation>
			<FundFamily>Fund Family</FundFamily>
			<AssetGroup>Asset Group</AssetGroup>
			<FixedIncome Duration="Medium Term" Quality="High"/>
			<ExpenseRatio>.35</ExpenseRatio>
			<TotalAssets>8490000000</TotalAssets>
			<MinInitialInvestment>2500</MinInitialInvestment>
			<MinSubsequentInvestment>100</MinSubsequentInvestment>
		</FundInformation>
		<Description>
			<FundDescription>
PIMCO Total Return Fund seeks total return consistent with preservation of capital. The fund normally invests at <Assets>least 65% of assets in debt securities</Assets>, including U.S. government securities, corporate bonds, and mortgage-related securities. It may invest <Assets>up to 20% of assets in securities denominated in foreign currencies</Assets>. The fund may invest <Assets>up to 10% of assets in high yield securities</Assets> rated <Rating>B or higher</Rating>. The portfolio duration generally ranges from three to six years.
			</FundDescription>
			<Management>
				<Manager>William H. Gross, Lead Manager since 11-May-87</Manager>. 
Gross is founder and chief investment officer with Pacific Investment Management Company. Mr Gross and his bond team have twice been awarded Morningstars Fixed-Income Manager of the Year award, in 1998 and 2000. In a 1993 survey by Pensions and Investments magazine, he was recognized by his peers as the most influential authority on the bond market in the United States. Gross is a Chartered Financial Analyst and a member of the Los Angeles Society of Financial Analysts. 
			</Management>
		</Description>
	</SecurityInformation>
	<Price>
		<LastTrade>86.23</LastTrade>
		<Ask>38.12</Ask>
		<Bid>34.78</Bid>
		<Price50DayAvg>35.37</Price50DayAvg>
		<Price200DayAvg>30.21</Price200DayAvg>
		<PriceToday>
			<PreviousClose>36.07</PreviousClose>
			<Open>36.23</Open>
			<Low>36.23</Low>
			<High>36.23</High>
		</PriceToday>
		<Price52week>
			<Price52week-low>29.44</Price52week-low>
			<Price52week-low-date>2002-05-12</Price52week-low-date>
			<Price52week-high>42.11</Price52week-high>
			<Price52week-high-date>2002-11-02</Price52week-high-date>
		</Price52week>
	</Price>
	<PE>17.13</PE>
	<Yield>0.94</Yield>
	<DivPerShare>1.64</DivPerShare>
</Security>

=== dctdevelopment/bagri/bagri-distr/src/main/data/tpox/security1500.xml
<?xml version="1.0" encoding="utf-8"?>
<Security id="1500" xmlns="http://tpox-benchmark.com/security"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tpox-benchmark.com/security security.xsd">
	<Symbol>VFINX</Symbol>
	<Name>Vanguard 500 Index Fund</Name>
	<ShortName>Vanguard 500 Idx </ShortName>
	<SecurityType>Stock Fund</SecurityType>
	<SecurityInformation>
		<FundInformation>
			<FundFamily>Fund Family</FundFamily>
			<AssetGroup>Asset Group</AssetGroup>
			<Category Capitalization="Large" Class="Blend"/>
			<ExpenseRatio>.18</ExpenseRatio>
			<TotalAssets>53000000000</TotalAssets>
			<MinInitialInvestment>3000</MinInitialInvestment>
			<MinSubsequentInvestment>100</MinSubsequentInvestment>
		</FundInformation>
		<Description>
			<FundDescription>
The fund seeks to track the performance of a benchmark index that measures the investment return of large-capitalization stocks.
The fund employs a "passive management" or indexing investment approach designed to track the performance of the Standard &amp; Poor's 500 Index, a widely recognized benchmark of U.S. stock market performance that is dominated by the stocks of large U.S. companies. The fund attempts to replicate the target index by investing all, or substantially all, of its assets in the stocks that make up the index, holding each stock in approximately the same proportion as its weighting within the index. 
Though the fund seeks to track the index, its performance typically will fall short by a small percentage representing operating costs. 
The fund reserves the right to invest, to a limited extent, in stock futures and options contracts, warrants, convertible securities, and swap agreements, which are types of derivatives. It may use these investments for two reasons: to keep cash on hand to meet shareholder redemptions or other needs while simulating full investment in stocks or to reduce costs by buying futures instead of actual stocks when futures are cheaper. Losses (or gains) involving futures and options contracts can be substantial in part because a relatively small price movement in a contract may result in an immediate and substantial loss (or gain) for the fund. Similar risks exist for warrants, convertible securities, and swap agreements. For this reason, the fund will not use such investments for speculative purposes. Only a limited percentage of its assets may be committed to them. 
Vanguard funds classified as moderate to aggressive are broadly diversified but are subject to wide fluctuations in share price because they hold virtually all of their assets in common stocks. In general, such funds are appropriate for investors who have a long investment horizon (ten years or longer), who are seeking growth in capital as a primary objective, and who are prepared to endure the sharp and sometimes prolonged declines in share prices that occur from time to time in the stock market. This price volatility is the trade-off for the potentially high returns that common stocks can provide. The level of current income produced by funds in this category ranges from moderate to very low. 
			</FundDescription>
			<Management>
				<Manager>George U. Sauter Lead Manager since 05-Oct-87 </Manager> Sauter is a managing director of The Vanguard Group, his employer since 1987. He has managed portfolio investments since 1987 and has worked in investment management since 1985. 
			</Management>
		</Description>
	</SecurityInformation>
	<Price>
		<LastTrade>102.77</LastTrade>
		<Ask>102.85</Ask>
		<Bid>102.63</Bid>
		<Price50DayAvg>95.24</Price50DayAvg>
		<Price200DayAvg>97.12</Price200DayAvg>
		<PriceToday>
			<PreviousClose>101.12</PreviousClose>
			<Open>101.12</Open>
			<Low>101.08</Low>
			<High>103.04</High>
		</PriceToday>
		<Price52week>
			<Price52week-low>78.11</Price52week-low>
			<Price52week-low-date>2004-03-05</Price52week-low-date>
			<Price52week-high>107.34</Price52week-high>
			<Price52week-high-date>2003-07-19</Price52week-high-date>
		</Price52week>
	</Price>
	<PE>21.1</PE>
	<Yield>1.44</Yield>
	<DivPerShare>1.97</DivPerShare>
</Security>
