=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/workload_properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="workload">
		<xs:complexType>
			<xs:sequence>
                <xs:element ref="collections" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="directory" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="transactions" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="collections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="collection" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="collection">
		<xs:complexType>
			<xs:all>
				<xs:element name="ids" minOccurs="0">
				</xs:element>
				<xs:element name="files" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="dir" type="xs:string" use="required"/>
						<xs:attribute name="firstfileid" type="xs:integer" use="required"/>
						<xs:attribute name="lastfileid" type="xs:integer" use="required"/>
						<xs:attribute name="docsperfile" type="xs:integer" use="required"/>
						<xs:attribute name="fileprefix" type="xs:string" use="optional"/>
						<xs:attribute name="filepostfix" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:all>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="directory" type="xs:string"/>
	<xs:element name="transactions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transaction" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="transaction">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="location" minOccurs="0"/>
					<xs:element ref="statements" minOccurs="0"/>
					<xs:element ref="java-plugin" minOccurs="0"/>
				</xs:choice>
				<xs:element ref="parameters" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="weight" type="xs:float" use="optional"/>
			<xs:attribute name="id" type="xs:integer" use="optional"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="location" type="xs:string">		<!-- 
		<xs:complexType>
			<xs:attribute name="delimiter" type="xs:string" use="optional"/>
		</xs:complexType>
		 -->
	</xs:element>
	<xs:element name="statements">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="statement" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="statement" type="xs:string"/>
	<xs:element name="java-plugin" type="xs:string"/>
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="ids"/>
				<xs:element ref="files"/>
				<xs:element ref="filesclob"/>
				<xs:element ref="file"/>
				<xs:element ref="file_seq"/>
				<xs:element ref="uniformint"/>
				<xs:element ref="uniformdec"/>
				<xs:element ref="uniform_int"/>
				<xs:element ref="uniform_dec"/>
				<xs:element ref="uniform_date"/>
				<xs:element ref="uniform_time"/>
				<xs:element ref="uniform_timestamp"/>
				<xs:element ref="constant"/>
				<xs:element ref="sequence"/>
				<xs:element ref="same"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="ids">
		<xs:complexType>
			<xs:attribute name="collection" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="files">
		<xs:complexType>
			<xs:attribute name="collection" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="filesclob">
		<xs:complexType>
			<xs:attribute name="collection" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="file" type="xs:string"/>
	<xs:element name="file_seq" type="xs:string"/>
	<xs:element name="uniformint">
	<!-- @deprecated -->
		<xs:complexType>
			<xs:attribute name="min" type="xs:int" use="required"/>
			<xs:attribute name="max" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="uniformdec">
	<!-- @deprecated -->
		<xs:complexType>
			<xs:attribute name="min" type="xs:float" use="required"/>
			<xs:attribute name="max" type="xs:float" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="uniform_int">
		<xs:complexType>
			<xs:attribute name="min" type="xs:int" use="required"/>
			<xs:attribute name="max" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="uniform_dec">
		<xs:complexType>
			<xs:attribute name="min" type="xs:float" use="required"/>
			<xs:attribute name="max" type="xs:float" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="uniform_date">
		<xs:complexType>
			<xs:attribute name="start" type="xs:date" use="required"/>
			<xs:attribute name="end" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="uniform_time">
		<xs:complexType>
			<xs:attribute name="start" type="xs:time" use="required"/>
			<xs:attribute name="end" type="xs:time" use="required"/>
			<xs:attribute name="base_date" type="xs:date" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="uniform_timestamp">
		<xs:complexType>
			<xs:attribute name="start" type="xs:date" use="required"/>
			<xs:attribute name="end" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="constant">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sequence">
		<xs:complexType>
			<xs:attribute name="start" type="xs:int" use="required"/>
			<xs:attribute name="step" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="same">
		<xs:complexType>
			<xs:attribute name="param" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/XCC/insSecurity.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="queries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="security">
			<files dir="/data/security" firstfileid="1" lastfileid="1" docsperfile="20833" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
	</collections>
	<transactions>

		<transaction id="1" name="addSecurity" weight="100">
			<java-plugin>com.bagri.client.tpox.workload.MarkLogicXCCPlugin</java-plugin>
			<parameters>
				<parameter>
					<constant value="insertDocument" />
				</parameter>
				<parameter>
					<constant value="false" />
				</parameter>
				<parameter>
					<constant value="doc" />
				</parameter>
				<parameter>
					<constant value="document" />
				</parameter>
				<parameter>
					<files collection="security"/>
				</parameter>
				<parameter>
					<constant value="prefix" />
				</parameter>
				<parameter>
					<constant value="string" />
				</parameter>
				<parameter>
					<constant value="security" />
				</parameter>
				<parameter>
					<constant value="collect" />
				</parameter>
				<parameter>
					<constant value="string" />
				</parameter>
				<parameter>
					<constant value="securities" />
				</parameter>
			</parameters>
		</transaction>

		<!--transaction id="1" name="addSecurity" weight="100">
			<java-plugin>com.bagri.client.tpox.workload.MarkLogicXCCPlugin</java-plugin>
			<parameters>
				<parameter>
					<constant value="
(: declare namespace bgdb=&quot;http://bagridb.com/bdb&quot;; :)
declare variable $sec external;
declare variable $uri external;
xdmp:document-insert($uri, $sec, xdmp:default-permissions(), &quot;securities&quot;)" />
				</parameter>
				<parameter>
					<constant value="true" />
				</parameter>
				<parameter>
					<constant value="sec" />
				</parameter>
				<parameter>
					<constant value="document" />
				</parameter>
				<parameter>
					<files collection="security"/>
				</parameter>
				<parameter>
					<constant value="uri" />
				</parameter>
				<parameter>
					<constant value="string" />
				</parameter>
				<parameter>
					<constant value="sec + ..." />
				</parameter>
			</parameters>
		</transaction-->
	</transactions>
</workload>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/XDM/insSecurity.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="insertSecurities" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="security">
			<files dir="/data/security" firstfileid="1" lastfileid="1" docsperfile="20833" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
	</collections>
	<transactions>

		<transaction id="1" name="addDocument" weight="100">
			<java-plugin>com.bagri.client.tpox.workload.BagriXDMPlugin</java-plugin>
			<parameters>
				<parameter>
					<files collection="security"/>
				</parameter>
			</parameters>
		</transaction>

	</transactions>
</workload>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/insSecurity-xqj-ml.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="queries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="security">
			<files dir="/data/security" firstfileid="1" lastfileid="1" docsperfile="20833" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
	</collections>
	<transactions>

		<!--transaction id="1" name="addSecurity" weight="100">
			<java-plugin>com.bagri.client.tpox.workload.BagriXQJPlugin</java-plugin>
			<parameters>
				<parameter>
					<constant value="storeDocument($s)" />
				</parameter>
				<parameter>
					<constant value="false" />
				</parameter>
				<parameter>
					<constant value="s" />
				</parameter>
				<parameter>
					<constant value="document" />
				</parameter>
				<parameter>
					<files collection="security"/>
				</parameter>
			</parameters>
		</transaction-->

		<transaction id="1" name="addSecurity" weight="100">
			<java-plugin>com.bagri.client.tpox.workload.MarkLogicXQJPlugin</java-plugin>
			<parameters>
				<parameter>
					<constant value="insertDocument" />
				</parameter>
				<parameter>
					<constant value="false" />
				</parameter>
				<parameter>
					<constant value="doc" />
				</parameter>
				<parameter>
					<constant value="document" />
				</parameter>
				<parameter>
					<files collection="security"/>
				</parameter>
			</parameters>
		</transaction>
	</transactions>
</workload>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/insOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="insertOrders" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="order">
			<files dir="/data/order" firstfileid="1" lastfileid="1" docsperfile="500000" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
	</collections>
	<transactions>

		<transaction id="1" name="addDocument" weight="100">
			<java-plugin>com.bagri.client.tpox.workload.BagriXDMPlugin</java-plugin>
			<parameters>
				<parameter>
					<files collection="order"/>
				</parameter>
			</parameters>
		</transaction>

	</transactions>
</workload>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/XDM/securities.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="queries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="security">
			<files dir="/data/security" firstfileid="1" lastfileid="1" docsperfile="20833" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
	</collections>
	<transactions>
		<!--transaction id="1" name="addDocument" weight="25">
			<java-plugin>com.bagri.test.tpox.workload.BagriXDMPlugin</java-plugin>
			<parameters>
				<parameter>
					<files collection="security"/>
				</parameter>
			</parameters>
		</transaction-->

		<transaction id="2" name="getSecurity" weight="50">
			<java-plugin>com.bagri.test.tpox.workload.BagriDBPlugin</java-plugin>
			<parameters>
				<parameter>
					<file>input/security_symbols.txt</file>
				</parameter>
			</parameters>
		</transaction>

		<transaction id="3" name="getSecurityPrice" weight="50">
			<java-plugin>com.bagri.test.tpox.workload.BagriDBPlugin</java-plugin>
			<parameters>
				<parameter>
					<file>input/security_symbols.txt</file>
				</parameter>
			</parameters>
		</transaction>

		<!--transaction id="4" name="searchSecurity" weight="30">
			<java-plugin>com.bagri.test.tpox.workload.BagriDBPlugin</java-plugin>
			<parameters>
				<parameter>
					<file>input/security_sectors.txt</file>
				</parameter>
				<parameter>
					<uniformint min="20" max="23"/>
				</parameter>
				<parameter>
					<uniformint min="25" max="27"/>
				</parameter>
				<parameter>
					<uniformint min="4" max="6"/>
				</parameter>
			</parameters>
		</transaction-->
	</transactions>
</workload>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/XCC/orders-40.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="queries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="order">
			<files dir="/data/order" firstfileid="1" lastfileid="1" docsperfile="40000" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
		<collection name="orderids">
			<ids first="103282" last="143281" />
		</collection>
	</collections>

	<transactions>
		<transaction id="1" name="getOrder" weight="100">
			<java-plugin>com.bagri.client.tpox.workload.MarkLogicXCCPlugin</java-plugin>
			<parameters>
				<parameter>
					<constant value="
declare namespace o=&quot;http://www.fixprotocol.org/FIXML-4-4&quot;;
declare variable $ID external;

for $ord in fn:collection(&quot;orders&quot;)/o:FIXML
where $ord/o:Order/@ID=$ID
return $ord/o:Order" />
				</parameter>
				<parameter>
					<constant value="true" />
				</parameter>
				<parameter>
					<constant value="ID" />
				</parameter>
				<parameter>
					<constant value="string" />
				</parameter>
				<parameter>
					<ids collection="orderids" />
				</parameter>
			</parameters>
		</transaction>
	</transactions>
</workload>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/XDM/custaccs.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="queries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="custacc">
			<files dir="/data/custacc" firstfileid="1" lastfileid="2" docsperfile="50000" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
		<collection name="custids">
			<ids first="1002" last="101001" />
		</collection>
	</collections>
	<transactions>
		<transaction id="1" name="addDocument" weight="40">
			<java-plugin>com.bagri.test.tpox.workload.BagriDBPlugin</java-plugin>
			<parameters>
				<parameter>
					<files collection="custacc"/>
				</parameter>
			</parameters>
		</transaction>

		<transaction id="2" name="getCustomerProfile" weight="30">
			<java-plugin>com.bagri.test.tpox.workload.BagriDBPlugin</java-plugin>
			<parameters>
				<parameter>
					<ids collection="custids" />
				</parameter>
			</parameters>
		</transaction>

		<transaction id="3" name="getCustomerAccounts" weight="30">
			<java-plugin>com.bagri.test.tpox.workload.BagriDBPlugin</java-plugin>
			<parameters>
				<parameter>
					<ids collection="custids" />
				</parameter>
			</parameters>
		</transaction>
	</transactions>
</workload>

=== dctdevelopment/bagri/bagri-test/bagri-test-tpox/queries/XQJ/insAccount.xml
<?xml version="1.0" encoding="UTF-8"?>
<workload name="insertAccounts" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workload_properties.xsd">
	<collections>
		<collection name="account">
			<files dir="/data/account" firstfileid="1" lastfileid="1" docsperfile="50000" fileprefix="batch-" filepostfix="xml.offset"/>
		</collection>
	</collections>
	<transactions>

		<!--transaction id="1" name="addDocument" weight="100">
			<java-plugin>com.bagri.test.tpox.workload.BagriXQJPlugin</java-plugin>
			<parameters>
				<parameter>
					<constant value="
declare namespace bgdm=&quot;http://bagridb.com/bagri-xdm&quot;;
declare variable $doc external;

let $id := bgdm:store-document($doc)
return $id" />
				</parameter>
				<parameter>
					<constant value="true" />
				</parameter>
				<parameter>
					<constant value="doc" />
				</parameter>
				<parameter>
					<constant value="document" />
				</parameter>
				<parameter>
					<files collection="account"/>
				</parameter>
			</parameters>
		</transaction-->

		<transaction id="1" name="addDocument" weight="100">
			<java-plugin>com.bagri.test.tpox.workload.BagriXQJPlugin</java-plugin>
			<parameters>
				<parameter>
					<constant value="store-document" />
				</parameter>
				<parameter>
					<constant value="false" />
				</parameter>
				<parameter>
					<constant value="content" />
				</parameter>
				<parameter>
					<constant value="document" />
				</parameter>
				<parameter>
					<files collection="account"/>
				</parameter>
				<parameter>
					<constant value="docId" />
				</parameter>
				<parameter>
					<constant value="int" />
				</parameter>
				<parameter>
					<sequence start="1" step="1"/>
				</parameter>
			</parameters>
		</transaction>

	</transactions>
</workload>
